/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import business.Account;
import business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shreyas
 */
public class ViewAccountJPanel extends javax.swing.JPanel {
        private JPanel userProcessContainer;
private AccountDirectory accountDirectory;

private Account account;

    /**
     * Creates new form ViewAccountJPanel
     */
   
    ViewAccountJPanel(JPanel userProcessContainer, Account account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        populateAccountDetails();
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
//        populateTable();
    }
    
    private void populateAccountDetails(){
txtRoutingNumber.setText(account.getRoutingNumber());
txtAccountNumber.setText(account.getAccountNumber());
txtBankName.setText(account.getBankName());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtRoutingNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAccountNumber = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 328, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 328, -1, -1));

        txtRoutingNumber.setEnabled(false);
        txtRoutingNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoutingNumberActionPerformed(evt);
            }
        });
        txtRoutingNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRoutingNumberKeyPressed(evt);
            }
        });
        add(txtRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 145, 191, -1));

        jLabel3.setText("Account Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 186, -1, -1));

        txtAccountNumber.setEnabled(false);
        txtAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAccountNumberKeyPressed(evt);
            }
        });
        add(txtAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 186, 191, -1));

        txtBankName.setEnabled(false);
        txtBankName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBankNameKeyPressed(evt);
            }
        });
        add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 227, 191, -1));

        jLabel1.setText("View Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 42, -1, -1));

        jButton2.setText("< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 485, -1, -1));

        jLabel2.setText("Routing Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 148, -1, -1));

        jLabel4.setText("Bank Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 227, -1, -1));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 148, -1, -1));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 174, -1, -1));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 201, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoutingNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoutingNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoutingNumberActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        account.setRoutingNumber(txtRoutingNumber.getText());
        account.setAccountNumber(txtAccountNumber.getText());
        account.setBankName(txtBankName.getText());
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Account Updated Succesfully");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtRoutingNumber.setEnabled(true);
        txtBankName.setEnabled(true);
        txtAccountNumber.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtRoutingNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoutingNumberKeyPressed
char c = evt.getKeyChar () ;
// TODO add your handling code here:

//if (Character.isLetter(c) ||Character.isWhitespace(c) || Character.isISOControl(c)) {
if (Character.isLetter(c)) {

            txtRoutingNumber.setEditable(false);
            jLabel7.setText("Please Numbers only");
            
}
else {
    txtRoutingNumber.setEditable(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoutingNumberKeyPressed

    private void txtAccountNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountNumberKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar () ;
// TODO add your handling code here:

//if (Character.isLetter(c) ||Character.isWhitespace(c) || Character.isISOControl(c)) {
if (Character.isLetter(c)) {

            txtAccountNumber.setEditable(false);
            jLabel7.setText("Please Input Numbers only");
            
}
else {
    txtAccountNumber.setEditable(true);
}        // T
    }//GEN-LAST:event_txtAccountNumberKeyPressed

    private void txtBankNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankNameKeyPressed
   char c = evt.getKeyChar () ;
// TODO add your handling code here:

if (Character.isLetter(c) ||Character.isWhitespace(c) || Character.isISOControl(c)) {
//if (Character.isLetter(c)) || {

            txtBankName.setEditable(true);
            
}
else {
    txtBankName.setEditable(false);
                jLabel8.setText("No Numbers, Please enter text only");

}       
    }//GEN-LAST:event_txtBankNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtRoutingNumber;
    // End of variables declaration//GEN-END:variables
}
